//
// Created by Matthias on 12.11.20.
//

#ifndef PRAKTIKUM3_KONSTANTEN_H
#define PRAKTIKUM3_KONSTANTEN_H
#define ARRAY_SIZE 1024
#define SUBS_SIZE 29
#define SUBS_STATES 2
#define PRIMZAHLEN_BIS 10000

#endif //PRAKTIKUM3_KONSTANTEN_H
